# Generated by Django 3.1.7 on 2021-05-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
